Repository LaCoolCo/LaCOOLBoard, pull requests merged in 2018-03, with the labels that each got.

#29 Do not send plaintext logs...
  src/CoolBoard.cpp
Labels: bug, high priority

#30 Fix/nomad leak
  src/CoolFileSystem.cpp
Labels: Blocker, bug

#33 Memory fix
  src/CoolBoard.cpp
  src/CoolFileSystem.cpp
  src/CoolFileSystem.h
Labels: Blocker, bug, high priority

#32 Get a easy way to start AP with the bootstrap switch
  src/CoolBoard.cpp
  src/CoolBoard.h
Labels: enhancement

#34 Better ntp
  README.md
  examples/AutoSprinkle/data/rtcConfig.json
  examples/Farm/data/rtcConfig.json
  examples/Station/data/rtcConfig.json
  examples/WeatherStation/data/rtcConfig.json
  src/CoolBoard.cpp
  src/CoolTime.cpp
  src/CoolTime.h
Labels: enhancement, medium priority
