Repository LaCoolCo/LaCOOLBoard, pull requests merged in 2018-06, with the labels that each got.

#68 Add HTTPS OTA support
  .gitignore
  .travis.yml
  patch/patch.sh
  platformio.ini
  src/core/CoolBoard.cpp
  src/core/CoolBoard.h
  src/core/CoolBoardLed.h
  src/core/CoolConfig.cpp
  src/core/CoolLog.h
  src/core/CoolWifi.h
Labels: in progress

#154 Add SDS011 microparticle sensor
  examples/SDS011/SDS011.ino
  examples/SDS011/data/coolBoardActorConfig.json
  examples/SDS011/data/coolBoardConfig.json
  examples/SDS011/data/coolBoardLedConfig.json
  examples/SDS011/data/coolBoardSensorsConfig.json
  examples/SDS011/data/externalSensorsConfig.json
  examples/SDS011/data/rtcConfig.json
  examples/SDS011/data/wifiConfig.json
  src/core/ExternalSensor.h
  src/core/ExternalSensors.cpp
  src/extras/CoolSDS011.cpp
  src/extras/CoolSDS011.h
Labels: enhancement

#160 Fix IRN3000 calibration procedure
  src/core/CoolBoardLed.h
  src/core/Irene3000.cpp
Labels: bug, enhancement
